export const headerBackTitle = "Trở lại";
export const home = "Trang chủ";
export const account = "Tài khoản";
export const schedule = "Lịch & nhật ký bệnh";
export const diary = "Nhật ký";
export const noSchedule = "Không có nhắc nhở hôm nay";
export const addDate = "Thêm nhắc nhở";
export const alertName = "Thông báo";
export const alertInfo = "Vui lòng nhập ngày và nội dung sự kiện";
export const shareHealthLog = "Chia sẻ Nhật ký Bệnh";
export const share = "Chia sẻ";
export const signIn = "ĐĂNG NHẬP";
export const signInGoogle = "ĐĂNG NHẬP VỚI GOOGLE";
export const appName = "Senior Health Diary";
export const forgotPassword = "Quên mật khẩu?";
export const errorResponse = "Đã có lỗi xảy ra";
export const optionText = "Tuỳ chọn";
export const ageText = "Tuổi"
